PRESS_UP_BUTTON	PROC	NEAR
	PUSH	BP
	MOV	BP,SP					;[BP+4]=LEFT,[BP+6]=TOP,[BP+8]=PTEXT(POINT STRING),[BP+10]=COLOR
	SUB	SP,6
	PUSH	SI
	PUSH	DI
	MOV	SI,WORD PTR [BP+4]
	MOV	DI,WORD PTR [BP+6]
   ;
	PUSH	WORD PTR [BP+8]
	CALL	NEAR PTR STRLEN
	POP	CX
	MOV	WORD PTR [BP-2],AX					;LENGTH OF STING->[BP-2]
  ;	
	MOV	AX,WORD PTR [BP-2]
	ADD	AX,4
	MOV	CL,3
	SHL	AX,CL
	;XOR	AH,AH								;若要修改,注意此段
	;MOV	DL,BYTE PTR CHARWIDTH
	;MUL	DL
	MOV	DX,SI
	ADD	DX,AX
	DEC	DX
	MOV	WORD PTR [BP-4],DX					;[BP-4]=RIGHT
   ;
	MOV	AX,DI
	ADD	AX,DEFAULTBUTTONHEIGHT
	DEC	AX
	MOV	WORD PTR [BP-6],AX					;[BP-6]=BOTTOM
  ;	
	MOV	AX,WHITE
	PUSH	AX
	PUSH	DI
	PUSH	WORD PTR [BP-4]
	PUSH	SI
	CALL	NEAR PTR HLINE
	ADD	SP,8
  ;	
	MOV	AX,WHITE
	PUSH	AX
	PUSH	SI
	PUSH	WORD PTR [BP-6]
	PUSH	DI
	CALL	NEAR PTR VLINE
	ADD	SP,8
  ;	
	MOV	AX,LIGHTBLACK
	PUSH	AX
	MOV	AX,WORD PTR [BP-6]
	DEC	AX
	PUSH	AX
	MOV	AX,WORD PTR [BP-4]
	DEC	AX
	PUSH	AX
	MOV	AX,SI
	INC	AX
	PUSH	AX
	CALL	NEAR PTR HLINE
	ADD	SP,8
  ;
	MOV	AX,DARKBLACK
	PUSH	AX
	PUSH	WORD PTR [BP-6]
	PUSH	WORD PTR [BP-4]
	PUSH	SI
	CALL	NEAR PTR HLINE
	ADD	SP,8
  ;	
	MOV	AX,LIGHTBLACK
	PUSH	AX
	MOV	AX,WORD PTR [BP-4]
	DEC	AX
	PUSH	AX
	MOV	AX,WORD PTR [BP-6]
	DEC	AX
	PUSH	AX
	MOV	AX,DI
	INC	AX
	PUSH	AX
	CALL	NEAR PTR VLINE
	ADD	SP,8
 ;
	MOV	AX,DARKBLACK
	PUSH	AX
	PUSH	WORD PTR [BP-4]
	PUSH	WORD PTR [BP-6]
	PUSH	DI
	CALL	NEAR PTR VLINE
	ADD	SP,8
   ;		PUTSTR(LEFT+CHARWIDTH*2,TOP+CHARHEIGHT/2,PTEXT,COLOR);
	;PUSH	WORD PTR [BP+10]
	;PUSH	WORD PTR [BP+8]
	;MOV	AX,CHARHEIGHT
	;SHR	AX,1
	;ADD	AX,[BP+6]
	;PUSH	AX
	;MOV	AX,CHARWIDTH
	;SHL	AX,1
	;ADD	AX,[BP+4]
	;PUSH	AX
	;CALL	NEAR PTR PUTSTR
	;ADD	SP,8
   ;
	POP	DI
	POP	SI
	MOV	SP,BP
	POP	BP
	RET	
PRESS_UP_BUTTON	ENDP

;
PRESS_DOWN_BUTTON	PROC	NEAR
	PUSH	BP
	MOV	BP,SP					;[BP+4]=LEFT,[BP+6]=TOP,[BP+8]=PTEXT(POINT STRING),[BP+10]=COLOR
	SUB	SP,6
	PUSH	SI
	PUSH	DI
	MOV	SI,WORD PTR [BP+4]
	MOV	DI,WORD PTR [BP+6]
   ;
	PUSH	WORD PTR [BP+8]
	CALL	NEAR PTR STRLEN
	POP	CX
	MOV	WORD PTR [BP-2],AX					;LENGTH OF STING->[BP-2]
  ;	
	MOV	AX,WORD PTR [BP-2]
	ADD	AX,4
	MOV	CL,3
	SHL	AX,CL
	;XOR	AH,AH								;若要修改,注意此段
	;MOV	DL,BYTE PTR CHARWIDTH
	;MUL	DL
	MOV	DX,SI
	ADD	DX,AX
	DEC	DX
	MOV	WORD PTR [BP-4],DX					;[BP-4]=RIGHT
   ;
	MOV	AX,DI
	ADD	AX,DEFAULTBUTTONHEIGHT
	DEC	AX
	MOV	WORD PTR [BP-6],AX					;[BP-6]=BOTTOM
  ;	
	MOV	AX,DARKBLACK				;顶端的颜色
	PUSH	AX
	PUSH	DI
	PUSH	WORD PTR [BP-4]
	PUSH	SI
	CALL	NEAR PTR HLINE
	ADD	SP,8
  ;	
	MOV	AX,DARKBLACK			;左边的颜色
	PUSH	AX
	PUSH	SI
	PUSH	WORD PTR [BP-6]
	PUSH	DI
	CALL	NEAR PTR VLINE
	ADD	SP,8
  ;	
	MOV	AX,WHITE	;底端的颜色
	PUSH	AX
	MOV	AX,WORD PTR [BP-6]
	DEC	AX
	PUSH	AX
	MOV	AX,WORD PTR [BP-4]
	DEC	AX
	PUSH	AX
	MOV	AX,SI
	INC	AX
	PUSH	AX
	CALL	NEAR PTR HLINE
	ADD	SP,8
  ;
	MOV	AX,LIGHTBLACK
	PUSH	AX
	PUSH	WORD PTR [BP-6]
	PUSH	WORD PTR [BP-4]
	PUSH	SI
	CALL	NEAR PTR HLINE
	ADD	SP,8
  ;	
	MOV	AX,WHITE
	PUSH	AX
	MOV	AX,WORD PTR [BP-4]
	DEC	AX
	PUSH	AX
	MOV	AX,WORD PTR [BP-6]
	DEC	AX
	PUSH	AX
	MOV	AX,DI
	INC	AX
	PUSH	AX
	CALL	NEAR PTR VLINE
	ADD	SP,8
 ;
	MOV	AX,LIGHTBLACK
	PUSH	AX
	PUSH	WORD PTR [BP-4]
	PUSH	WORD PTR [BP-6]
	PUSH	DI
	CALL	NEAR PTR VLINE
	ADD	SP,8
   ;		PUTSTR(LEFT+CHARWIDTH*2,TOP+CHARHEIGHT/2,PTEXT,COLOR);
	;PUSH	WORD PTR [BP+10]
	;PUSH	WORD PTR [BP+8]
	;MOV	AX,CHARHEIGHT
	;SHR	AX,1
	;ADD	AX,[BP+6]
	;PUSH	AX
	;MOV	AX,CHARWIDTH
	;SHL	AX,1
	;ADD	AX,[BP+4]
	;PUSH	AX
	;CALL	NEAR PTR PUTSTR
	;ADD	SP,8
   ;
	POP	DI
	POP	SI
	MOV	SP,BP
	POP	BP
	RET	
PRESS_DOWN_BUTTON	ENDP
;------------------------
;处理鼠标左键按下的动作
MOUSE_LBUTTON_DOWN_FUN	PROC	NEAR
	PUSHA
	PUSH ES
	;比较鼠标的按键区域是否落在了button内
	CLC
	MOV	AX,GL_MOUSE_XCORD
	CMP	AX,BUTTON_LEFT_WAI		;内外网的按钮是左对齐的，所以只要比较一次
	JAE	HOT_POINT_MORE_LEFT
	JMP	EXCEED_HOT_POINT
HOT_POINT_MORE_LEFT:
	CMP	AX,	BUTTON_LEFT_WAI+BUTTON_WIDTH
	JAE	EXCEED_HOT_POINT			;x超出范围
	MOV	AX,GL_MOUSE_YCORD
	CMP	AX,BUTTON_TOP_WAI
	JB	EXCEED_HOT_POINT			;y超出范围
	CMP	AX,BUTTON_TOP_WAI+DEFAULTBUTTONHEIGHT
	JA	EXCEED_HOT_POINT_WAI	;比较是否落在外网的按钮区域内
		;外网
		MOV	AX,RED
		PUSH	AX
		MOV	DX,OFFSET	STR_SYWAI
		PUSH	DX
		MOV	AX,BUTTON_TOP_WAI
		PUSH	AX
		MOV	AX,BUTTON_LEFT_WAI
		PUSH	AX
		CALL	PRESS_DOWN_BUTTON
		ADD	SP,8
		;
	JMP	HOT_POINT_DONE
EXCEED_HOT_POINT_WAI:			;接着比较是否落在内网的按钮区域内
	MOV	AX,GL_MOUSE_YCORD
	CMP	AX,BUTTON_TOP_NEI
	JB	EXCEED_HOT_POINT			;y没有落在热点内
	CMP	AX,BUTTON_TOP_NEI+DEFAULTBUTTONHEIGHT
	JA	EXCEED_HOT_POINT			;y没有落在热点内
		;内网
		MOV	AX,GREEN
		PUSH	AX
		MOV	DX,OFFSET	STR_SYNEI
		PUSH	DX
		MOV	AX,BUTTON_TOP_NEI
		PUSH	AX
		MOV	AX,BUTTON_LEFT_NEI
		PUSH	AX
		CALL	PRESS_DOWN_BUTTON
		ADD	SP,8	
		
EXCEED_HOT_POINT:
HOT_POINT_DONE:
	POP ES
	POPA
	RET
MOUSE_LBUTTON_DOWN_FUN	ENDP
;;----------------------------------------
;鼠标左键松开动作
MOUSE_LBUTTON_UP_FUN	PROC	NEAR
		PUSHA
		PUSH	ES
		MOV	AX,RED
		PUSH	AX
		MOV	DX,OFFSET	STR_SYWAI
		PUSH	DX
		MOV	AX,BUTTON_TOP_WAI
		PUSH	AX
		MOV	AX,BUTTON_LEFT_WAI
		PUSH	AX
		CALL	PRESS_UP_BUTTON
		ADD	SP,8	
		;
		MOV	AX,GREEN
		PUSH	AX
		MOV	DX,OFFSET	STR_SYNEI
		PUSH	DX
		MOV	AX,BUTTON_TOP_NEI
		PUSH	AX
		MOV	AX,BUTTON_LEFT_NEI
		PUSH	AX
		CALL	PRESS_UP_BUTTON
		ADD	SP,8
		;	
		POP	ES
		POPA
		RET
MOUSE_LBUTTON_UP_FUN	ENDP

;-----------------------------------------------------------------------------